### ISSUE TITLE
NullPointerException in MonitorChannelHandler

### ISSUE THREAD

**Issue by gbehrmann** [ivukotic/plugins#30]
A user has reported the following exception to us:

    09 Dec 2015 18:07:59 (f01-070-120-e_1D_cms) [door:Xrootd-f01-065-135-e:AAUmehV2R6A Xrootd-f01-065-135-e PoolDeliverFile 000046A308FB5E494015BC1E005A3DF45EAE] Transfer failed due to a bug
    java.lang.NullPointerException: null
       at edu.uchicago.monitor.MonitorChannelHandler.handleResponse(MonitorChannelHandler.java:183) [monitor-7.0.0.jar:na]
       at edu.uchicago.monitor.MonitorChannelHandler.write(MonitorChannelHandler.java:74) [monitor-7.0.0.jar:na]
       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633) [netty-transport-4.0.28.Final.jar:4.0.28.Final]
       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:691) [netty-transport-4.0.28.Final.jar:4.0.28.Final]
       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:626) [netty-transport-4.0.28.Final.jar:4.0.28.Final]
       at io.netty.handler.timeout.IdleStateHandler.write(IdleStateHandler.java:266) [netty-handler-4.0.28.Final.jar:4.0.28.Final]
       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633) [netty-transport-4.0.28.Final.jar:4.0.28.Final]
       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:691) [netty-transport-4.0.28.Final.jar:4.0.28.Final]
       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:626) [netty-transport-4.0.28.Final.jar:4.0.28.Final]
       at org.dcache.xrootd.stream.ChunkedResponseWriteHandler.write(ChunkedResponseWriteHandler.java:89) ~[xrootd4j-2.1.2.jar:2.1.2]
       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633) [netty-transport-4.0.28.Final.jar:4.0.28.Final]
       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:691) [netty-transport-4.0.28.Final.jar:4.0.28.Final]
       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:681) [netty-transport-4.0.28.Final.jar:4.0.28.Final]
       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:716) [netty-transport-4.0.28.Final.jar:4.0.28.Final]
       at org.dcache.xrootd.core.XrootdRequestHandler.respond(XrootdRequestHandler.java:204) [xrootd4j-2.1.2.jar:2.1.2]
       at org.dcache.xrootd.core.XrootdRequestHandler.requestReceived(XrootdRequestHandler.java:175) [xrootd4j-2.1.2.jar:2.1.2]
       at org.dcache.xrootd.core.XrootdRequestHandler.channelRead(XrootdRequestHandler.java:78) [xrootd4j-2.1.2.jar:2.1.2]
       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.28.Final.jar:4.0.28.Final]
       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.28.Final.jar:4.0.28.Final]
       at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-transport-4.0.28.Final.jar:4.0.28.Final]
       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.28.Final.jar:4.0.28.Final]
       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.28.Final.jar:4.0.28.Final]
       at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:254) [netty-handler-4.0.28.Final.jar:4.0.28.Final]
       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.28.Final.jar:4.0.28.Final]
       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.28.Final.jar:4.0.28.Final]
       at edu.uchicago.monitor.MonitorChannelHandler.channelRead(MonitorChannelHandler.java:63) [monitor-7.0.0.jar:na]
       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.28.Final.jar:4.0.28.Final]
       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.28.Final.jar:4.0.28.Final]
       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244) [netty-codec-4.0.28.Final.jar:4.0.28.Final]
       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.28.Final.jar:4.0.28.Final]
       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.28.Final.jar:4.0.28.Final]
       at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-transport-4.0.28.Final.jar:4.0.28.Final]
       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.28.Final.jar:4.0.28.Final]
       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.28.Final.jar:4.0.28.Final]
       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) [netty-transport-4.0.28.Final.jar:4.0.28.Final]
       at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [netty-transport-4.0.28.Final.jar:4.0.28.Final]
       at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [netty-transport-4.0.28.Final.jar:4.0.28.Final]
       at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [netty-transport-4.0.28.Final.jar:4.0.28.Final]
       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [netty-transport-4.0.28.Final.jar:4.0.28.Final]
       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [netty-transport-4.0.28.Final.jar:4.0.28.Final]
       at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111) [netty-common-4.0.28.Final.jar:4.0.28.Final]
       at org.dcache.util.CDCThreadFactory$1.run(CDCThreadFactory.java:53) [dcache-core-2.13.9.jar:2.13.9]
       at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]

This error is triggering by the following line in the plugin:

    fs.filesize = OR.getFileStatus().getSize();

The plugin assumes that the response always contains a file status, but this file status is optional as the client may not choose to request a stat response during open. Thus if a client opens a file without setting the kXR_retstat flag, the plugin fails with a NPE.

**Comment by gbehrmann** [comment]
Possibly a duplicate of #29.

**Comment by ivukotic** [comment]
fixed now.

**Comment by martbhell** [comment]
Is there an RPM released with the fix?
